<?php
return [
    'travels' => [
        [
            'image' => 'https://a0.muscache.com/im/pictures/miso/Hosting-13172628/original/456667ff-ddf4-48ff-ada6-0d1ab32a0f2c.jpeg?im_w=1200',
            'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque repudiandae quis officia placeat rerum at, alias quam! Accusantium nostrum explicabo consequatur mollitia nihil porro incidunt hic sed nobis nulla temporibus, omnis modi eveniet impedit. Ipsum non iusto porro, impedit consequuntur nesciunt,',
            'is_avaible' => true,
            'date_check_in' => '2022-08-01',
            'date_check_out' => '2022-08-07',
            'number_of_people' => '2',
            'type_of_person' => 'Adult',
            'location' => 'Sicily, Solanto',
            'type_of_location' => 'Beach',
            'price' => 700,
        ],
        [
            'image' => 'https://a0.muscache.com/im/pictures/ff4683c6-6a9a-43d3-a535-b8d23b90fc53.jpg?im_w=1440',
            'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque repudiandae quis officia placeat rerum at, alias quam! Accusantium nostrum explicabo consequatur mollitia nihil porro incidunt hic sed nobis nulla temporibus, omnis modi eveniet impedit. Ipsum non iusto porro, impedit consequuntur nesciunt,',
            'is_avaible' => true,
            'date_check_in' => '2022-08-07',
            'date_check_out' => '2022-08-014',
            'number_of_people' => '6',
            'type_of_person' => 'Adult',
            'location' => 'Sicily, Cefalù',
            'type_of_location' => 'Beach',
            'price' => 900,
        ],
        [
            'image' => 'https://a0.muscache.com/im/pictures/a30a03a6-75ec-4200-859d-21025fac8153.jpg?im_w=1200',
            'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque repudiandae quis officia placeat rerum at, alias quam! Accusantium nostrum explicabo consequatur mollitia nihil porro incidunt hic sed nobis nulla temporibus, omnis modi eveniet impedit. Ipsum non iusto porro, impedit consequuntur nesciunt,',
            'is_avaible' => true,
            'date_check_in' => '2022-08-12',
            'date_check_out' => '2022-08-18',
            'number_of_people' => '6',
            'type_of_person' => 'Adult',
            'location' => 'Sicily, Avola',
            'type_of_location' => 'Beach',
            'price' => 1200,
        ],
        [
            'image' => 'https://a0.muscache.com/im/pictures/92911101/89068635_original.jpg?im_w=1200',
            'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque repudiandae quis officia placeat rerum at, alias quam! Accusantium nostrum explicabo consequatur mollitia nihil porro incidunt hic sed nobis nulla temporibus, omnis modi eveniet impedit. Ipsum non iusto porro, impedit consequuntur nesciunt,',
            'is_avaible' => true,
            'date_check_in' => '2022-08-04',
            'date_check_out' => '2022-08-07',
            'number_of_people' => '2',
            'type_of_person' => 'Adult',
            'location' => 'Sicily, Augusta',
            'type_of_location' => 'Beach',
            'price' => 600,
        ],
        [
            'image' => 'https://a0.muscache.com/im/pictures/03e3189f-f228-4e78-a5b9-0e31bc2a5486.jpg?im_w=1200',
            'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque repudiandae quis officia placeat rerum at, alias quam! Accusantium nostrum explicabo consequatur mollitia nihil porro incidunt hic sed nobis nulla temporibus, omnis modi eveniet impedit. Ipsum non iusto porro, impedit consequuntur nesciunt,',
            'is_avaible' => true,
            'date_check_in' => '2022-08-11',
            'date_check_out' => '2022-08-12',
            'number_of_people' => '8',
            'type_of_person' => 'Adult',
            'location' => 'Sicily, Messina',
            'type_of_location' => 'Beach',
            'price' => 1600,
        ],
        [
            'image' => 'https://a0.muscache.com/im/pictures/1e9709ec-6bd5-48eb-bb4d-96698deab1a6.jpg?im_w=1200',
            'description' => 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque repudiandae quis officia placeat rerum at, alias quam! Accusantium nostrum explicabo consequatur mollitia nihil porro incidunt hic sed nobis nulla temporibus, omnis modi eveniet impedit. Ipsum non iusto porro, impedit consequuntur nesciunt,',
            'is_avaible' => true,
            'date_check_in' => '2022-08-12',
            'date_check_out' => '2022-08-15',
            'number_of_people' => '10+',
            'type_of_person' => 'Adult',
            'location' => 'Sicily, Marinella',
            'type_of_location' => 'Beach',
            'price' => 1900,
        ],

    ]
];
